version: "3.8"

services:
  app:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    container_name: favorite_content_app_dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
      NODE_ENV: development
      PORT: 3000
      API_VERSION: 1.0.0
      LOG_LEVEL: debug
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    command: npm run dev

  db:
    image: postgres:16
    container_name: postgres_container_dev
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
